//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.09 at 11:45:40 AM BRT 
//


package io.spring.guides.gs_producing_web_service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VendaFornecedor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VendaFornecedor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="idFornecedor" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="codigoProdutoLiberado" type="{http://spring.io/guides/gs-producing-web-service}ItemVendaFornecedor" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VendaFornecedor", propOrder = {
    "id",
    "idFornecedor",
    "codigoProdutoLiberado"
})
public class VendaFornecedor {

    protected int id;
    protected int idFornecedor;
    @XmlElement(required = true)
    protected List<ItemVendaFornecedor> codigoProdutoLiberado;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the idFornecedor property.
     * 
     */
    public int getIdFornecedor() {
        return idFornecedor;
    }

    /**
     * Sets the value of the idFornecedor property.
     * 
     */
    public void setIdFornecedor(int value) {
        this.idFornecedor = value;
    }

    /**
     * Gets the value of the codigoProdutoLiberado property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the codigoProdutoLiberado property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCodigoProdutoLiberado().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ItemVendaFornecedor }
     * 
     * 
     */
    public List<ItemVendaFornecedor> getCodigoProdutoLiberado() {
        if (codigoProdutoLiberado == null) {
            codigoProdutoLiberado = new ArrayList<ItemVendaFornecedor>();
        }
        return this.codigoProdutoLiberado;
    }

}
